/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WikiDataSpinner {}
  interface WikiDataSpinnerAttributes extends StencilHTMLAttributes {}

  interface WikidataCaptchaJs {}
  interface WikidataCaptchaJsAttributes extends StencilHTMLAttributes {
    'onWikiIsHuman'?: (event: CustomEvent<boolean>) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WikiDataSpinner': Components.WikiDataSpinner;
    'WikidataCaptchaJs': Components.WikidataCaptchaJs;
  }

  interface StencilIntrinsicElements {
    'wiki-data-spinner': Components.WikiDataSpinnerAttributes;
    'wikidata-captcha-js': Components.WikidataCaptchaJsAttributes;
  }


  interface HTMLWikiDataSpinnerElement extends Components.WikiDataSpinner, HTMLStencilElement {}
  var HTMLWikiDataSpinnerElement: {
    prototype: HTMLWikiDataSpinnerElement;
    new (): HTMLWikiDataSpinnerElement;
  };

  interface HTMLWikidataCaptchaJsElement extends Components.WikidataCaptchaJs, HTMLStencilElement {}
  var HTMLWikidataCaptchaJsElement: {
    prototype: HTMLWikidataCaptchaJsElement;
    new (): HTMLWikidataCaptchaJsElement;
  };

  interface HTMLElementTagNameMap {
    'wiki-data-spinner': HTMLWikiDataSpinnerElement
    'wikidata-captcha-js': HTMLWikidataCaptchaJsElement
  }

  interface ElementTagNameMap {
    'wiki-data-spinner': HTMLWikiDataSpinnerElement;
    'wikidata-captcha-js': HTMLWikidataCaptchaJsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
