/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface UcSpinner {}
  interface UcSpinnerAttributes extends StencilHTMLAttributes {}

  interface WikidataCaptchaJs {}
  interface WikidataCaptchaJsAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'UcSpinner': Components.UcSpinner;
    'WikidataCaptchaJs': Components.WikidataCaptchaJs;
  }

  interface StencilIntrinsicElements {
    'uc-spinner': Components.UcSpinnerAttributes;
    'wikidata-captcha-js': Components.WikidataCaptchaJsAttributes;
  }


  interface HTMLUcSpinnerElement extends Components.UcSpinner, HTMLStencilElement {}
  var HTMLUcSpinnerElement: {
    prototype: HTMLUcSpinnerElement;
    new (): HTMLUcSpinnerElement;
  };

  interface HTMLWikidataCaptchaJsElement extends Components.WikidataCaptchaJs, HTMLStencilElement {}
  var HTMLWikidataCaptchaJsElement: {
    prototype: HTMLWikidataCaptchaJsElement;
    new (): HTMLWikidataCaptchaJsElement;
  };

  interface HTMLElementTagNameMap {
    'uc-spinner': HTMLUcSpinnerElement
    'wikidata-captcha-js': HTMLWikidataCaptchaJsElement
  }

  interface ElementTagNameMap {
    'uc-spinner': HTMLUcSpinnerElement;
    'wikidata-captcha-js': HTMLWikidataCaptchaJsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
